# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "0eb2197fae293b4fc8ed379aac93c422"
name = "branded-demand-app"
handle = "branded-demand-app-20"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true

[build]
dev_store_url = "codeinspire2.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_all_orders,read_assigned_fulfillment_orders,read_fulfillments,read_merchant_managed_fulfillment_orders,read_orders,read_products,read_third_party_fulfillment_orders,write_assigned_fulfillment_orders,write_fulfillments,write_merchant_managed_fulfillment_orders,write_orders,write_products,write_third_party_fulfillment_orders"

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]

[webhooks]
api_version = "2024-07"

[pos]
embedded = false
